variables:
  ENV_BASE_URL: geniussystems.com.np
stages:
  - build
  - deploy

build:
  stage: build
  except:
    - master
    - tags
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -f Dockerfile.dev  -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/$CI_PROJECT_PATH

build_prod:
  stage: build
  only:
    - tags
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH .
    - docker tag registry.gitlab.com/$CI_PROJECT_PATH registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_NAME
    - docker push registry.gitlab.com/$CI_PROJECT_PATH


deploy_dev:
  stage: deploy
  only:
    - dev
  image: "registry.gitlab.com/geniussystems/tools/kubectl:latest"
  script:
    - echo ${kube_config} |base64 -d > ~/.kube/config
    - sed -e "s/{{app_name}}/$CI_PROJECT_NAME/g" -e "s#{{image}}#registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_SHA#" -e "s/{{image_pull_secret}}/$image_pull_secret/" kube/deployment.yaml | kubectl apply -f -
    - sed -e "s/{{app_name}}/$CI_PROJECT_NAME/g" kube/service.yaml | kubectl apply -f -
    - sed -e "s/{{app_name}}/$CI_PROJECT_NAME/g" -e "s/{{host}}/ems.dev.$ENV_BASE_URL/" -e "s/{{tls_secret}}/dev-geniussystems/g" kube/ingress.yaml | kubectl apply -f -

  environment:
    name: dev
    url: https://ems.dev.$ENV_BASE_URL
