export const RESPONSE_LEAVEAPP_SUCCESS = 'RESPONSE_LEAVEAPP_SUCCESS';
export const PAGE_DETAIL_SUCCESS = 'PAGE_DETAIL_SUCCESS';

export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_ONE_EMPLOYEE_SUCCESS = 'LOAD_ONE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const SEARCH_EMPLOYEES_SUCCESS = 'SEARCH_EMPLOYEES_SUCCESS';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_OPTMISTIC = 'DELETE_EMPLOYEE_OPTMISTIC';

export const LOAD_USERDETAIL_SUCCESS = 'LOAD_USERDETAIL_SUCCESS';
export const CREATE_USERDETAIL_SUCCESS = 'CREATE_USERDETAIL_SUCCESS';
export const UPDATE_USERDETAIL_SUCCESS = 'UPDATE_USERDETAIL_SUCCESS';
export const DELETE_USERDETAIL_OPTMISTIC = 'DELETE_USERDETAIL_OPTMISTIC';

export const LOAD_USERCONTACT_SUCCESS = 'LOAD_USERCONTACT_SUCCESS';
export const CREATE_USERCONTACT_SUCCESS = 'CREATE_USERCONTACT_SUCCESS';
export const UPDATE_USERCONTACT_SUCCESS = 'UPDATE_USERCONTACT_SUCCESS';
export const DELETE_USERCONTACT_OPTMISTIC = 'DELETE_USERCONTACT_OPTMISTIC';

export const LOAD_USERDOCUMENT_SUCCESS = 'LOAD_USERDOCUMENT_SUCCESS';
export const CREATE_USERDOCUMENT_SUCCESS = 'CREATE_USERDOCUMENT_SUCCESS';
export const UPDATE_USERDOCUMENT_SUCCESS = 'UPDATE_USERDOCUMENT_SUCCESS';
export const DELETE_USERDOCUMENT_OPTMISTIC = 'DELETE_USERDOCUMENT_OPTMISTIC';

export const LOAD_USERACCOUNT_SUCCESS = 'LOAD_USERACCOUNT_SUCCESS';
export const CREATE_USERACCOUNT_SUCCESS = 'CREATE_USERACCOUNT_SUCCESS';
export const UPDATE_USERACCOUNT_SUCCESS = 'UPDATE_USERACCOUNT_SUCCESS';
export const DELETE_USERACCOUNT_OPTMISTIC = 'DELETE_USERACCOUNT_OPTMISTIC';

export const LOAD_USERFAMILY_SUCCESS = 'LOAD_USERFAMILY_SUCCESS';
export const CREATE_USERFAMILY_SUCCESS = 'CREATE_USERFAMILY_SUCCESS';
export const UPDATE_USERFAMILY_SUCCESS = 'UPDATE_USERFAMILY_SUCCESS';
export const DELETE_USERFAMILY_OPTMISTIC = 'DELETE_USERFAMILY_OPTMISTIC';

export const LOAD_USERIDENTITY_SUCCESS = 'LOAD_USERIDENTITY_SUCCESS';
export const CREATE_USERIDENTITY_SUCCESS = 'CREATE_USERIDENTITY_SUCCESS';
export const UPDATE_USERIDENTITY_SUCCESS = 'UPDATE_USERIDENTITY_SUCCESS';
export const DELETE_USERIDENTITY_OPTMISTIC = 'DELETE_USERIDENTITY_OPTMISTIC';

export const LOAD_USERINSURANCE_SUCCESS = 'LOAD_USERINSURANCE_SUCCESS';
export const CREATE_USERINSURANCE_SUCCESS = 'CREATE_USERINSURANCE_SUCCESS';
export const UPDATE_USERINSURANCE_SUCCESS = 'UPDATE_USERINSURANCE_SUCCESS';
export const DELETE_USERINSURANCE_OPTMISTIC = 'DELETE_USERINSURANCE_OPTMISTIC';

export const LOAD_USERLANGUAGE_SUCCESS = 'LOAD_USERLANGUAGE_SUCCESS';
export const CREATE_USERLANGUAGE_SUCCESS = 'CREATE_USERLANGUAGE_SUCCESS';
export const UPDATE_USERLANGUAGE_SUCCESS = 'UPDATE_USERLANGUAGE_SUCCESS';
export const DELETE_USERLANGUAGE_OPTMISTIC = 'DELETE_USERLANGUAGE_OPTMISTIC';

export const LOAD_USERQUALIFICATION_SUCCESS = 'LOAD_USERQUALIFICATION_SUCCESS';
export const CREATE_USERQUALIFICATION_SUCCESS = 'CREATE_USERQUALIFICATION_SUCCESS';
export const UPDATE_USERQUALIFICATION_SUCCESS = 'UPDATE_USERQUALIFICATION_SUCCESS';
export const DELETE_USERQUALIFICATION_OPTMISTIC = 'DELETE_USERQUALIFICATION_OPTMISTIC';

export const LOAD_USERSERVICE_SUCCESS = 'LOAD_USERSERVICE_SUCCESS';
export const CREATE_USERSERVICE_SUCCESS = 'CREATE_USERSERVICE_SUCCESS';
export const UPDATE_USERSERVICE_SUCCESS = 'UPDATE_USERSERVICE_SUCCESS';
export const DELETE_USERSERVICE_OPTMISTIC = 'DELETE_USERSERVICE_OPTMISTIC';

export const LOAD_USERSERVICEDETAIL_SUCCESS = 'LOAD_USERSERVICEDETAIL_SUCCESS';
export const CREATE_USERSERVICEDETAIL_SUCCESS = 'CREATE_USERSERVICEDETAIL_SUCCESS';
export const UPDATE_USERSERVICEDETAIL_SUCCESS = 'UPDATE_USERSERVICEDETAIL_SUCCESS';
export const DELETE_USERSERVICEDETAIL_OPTMISTIC = 'DELETE_USERSERVICEDETAIL_OPTMISTIC';

export const LOAD_USERSKILL_SUCCESS = 'LOAD_USERSKILL_SUCCESS';
export const CREATE_USERSKILL_SUCCESS = 'CREATE_USERSKILL_SUCCESS';
export const UPDATE_USERSKILL_SUCCESS = 'UPDATE_USERSKILL_SUCCESS';
export const DELETE_USERSKILL_OPTMISTIC = 'DELETE_USERSKILL_OPTMISTIC';

export const LOAD_CALENDAR_SUCCESS = 'LOAD_CALENDAR_SUCCESS';
export const LOAD_ONECALENDAR_SUCCESS = 'LOAD_ONECALENDAR_SUCCESS';
export const CREATE_CALENDAR_SUCCESS = 'CREATE_CALENDAR_SUCCESS';
export const UPDATE_CALENDAR_SUCCESS = 'UPDATE_CALENDAR_SUCCESS';
export const DELETE_CALENDAR_OPTMISTIC = 'DELETE_CALENDAR_OPTMISTIC';

export const LOAD_DEPARTMENT_ONFORM = 'LOAD_DEPARTMENT_ONFORM';
export const LOAD_ONE_DEPARTMENT_SUCCESS = 'LOAD_ONE_DEPARTMENT_SUCCESS';
export const LOAD_DEPARTMENTS_SUCCESS = 'LOAD_DEPARTMENTS_SUCCESS';
export const CREATE_DEPARTMENT_SUCCESS = 'CREATE_DEPARTMENT_SUCCESS';
export const UPDATE_DEPARTMENT_SUCCESS = 'UPDATE_DEPARTMENT_SUCCESS';
export const DELETE_DEPARTMENT_OPTMISTIC = 'DELETE_DEPARTMENT_OPTMISTIC';

export const LOAD_ONE_DESIGNATION_SUCCESS = 'LOAD_ONE_DESIGNATION_SUCCESS';
export const LOAD_DESIGNATIONS_SUCCESS = 'LOAD_DESIGNATIONS_SUCCESS';
export const CREATE_DESIGNATION_SUCCESS = 'CREATE_DESIGNATION_SUCCESS';
export const UPDATE_DESIGNATION_SUCCESS = 'UPDATE_DESIGNATION_SUCCESS';
export const DELETE_DESIGNATION_OPTMISTIC = 'DELETE_DESIGNATION_OPTMISTIC';

export const USER_LEAVE_TYPES_SUCCESS = 'USER_LEAVE_TYPES_SUCCESS';
export const LOAD_LEAVE_TYPES_SUCCESS = 'LOAD_LEAVE_TYPES_SUCCESS';
export const CREATE_LEAVE_TYPE_SUCCESS = 'CREATE_LEAVE_TYPE_SUCCESS';
export const UPDATE_LEAVE_TYPE_SUCCESS = 'UPDATE_LEAVE_TYPE_SUCCESS';
export const DELETE_LEAVETYPE_OPTMISTIC = 'DELETE_LEAVETYPE_OPTMISTIC';
export const LOAD_OBJECT_LEAVETYPES_SUCCESS = 'LOAD_OBJECT_LEAVETYPES_SUCCESS';

export const LOAD_OBJ_LEAVEAPP_SUCCESS = 'LOAD_OBJ_LEAVEAPP_SUCCESS';
export const LOAD_LEAVEAPP_SUCCESS = 'LOAD_LEAVEAPP_SUCCESS';
export const LOAD_LEAVEAPPLICATIONS_SUCCESS = 'LOAD_LEAVEAPPLICATIONS_SUCCESS';
export const LOAD_USER_LEAVEAPPLICATIONS_SUCCESS = 'LOAD_USER_LEAVEAPPLICATIONS_SUCCESS';
export const CREATE_LEAVEAPPLICATION_SUCCESS = 'CREATE_LEAVEAPPLICATION_SUCCESS';
export const APPROVE_LEAVEAPPLICATION_SUCCESS = 'APPROVE_LEAVEAPPLICATION_SUCCESS';
export const CANCEL_LEAVEAPPLICATION_SUCCESS = 'CANCEL_LEAVEAPPLICATION_SUCCESS';
export const DELETE_LEAVEAPPLICATION_OPTMISTIC = 'DELETE_LEAVEAPPLICATION_OPTMISTIC';

export const LOAD_USER_LEAVEBALANCES_SUCCESS = 'LOAD_USER_LEAVEBALANCES_SUCCESS';
export const CREATE_LEAVEBALANCE_SUCCESS = 'CREATE_LEAVEBALANCE_SUCCESS';
export const UPDATE_LEAVEBALANCE_SUCCESS = 'UPDATE_LEAVEBALANCE_SUCCESS';
export const APPROVE_LEAVEBALANCE_SUCCESS = 'APPROVE_LEAVEBALANCE_SUCCESS';
export const CANCEL_LEAVEBALANCE_SUCCESS = 'CANCEL_LEAVEBALANCE_SUCCESS';
export const DELETE_LEAVEBALANCE_OPTMISTIC = 'DELETE_LEAVEBALANCE_OPTMISTIC';

export const EMP_ROLE_SUCCESS = 'EMP_ROLE_SUCCESS';
export const LOAD_COUNTRIES_SUCCESS = 'LOAD_COUNTRIES_SUCCESS';
export const EMP_STATUS_SUCCESS = 'EMP_STATUS_SUCCESS';
export const ACCESS_LINK_SUCCESS = 'ACCESS_LINK_SUCCESS';
export const FISCAL_YEAR_SUCCESS = 'FISCAL_YEAR_SUCCESS';

export const BEGIN_API_CALL = 'BEGIN_API_CALL';
export const API_CALL_ERROR = 'API_CALL_ERROR';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS';

export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS';
