apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{app_name}}-service
  name: {{app_name}}-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    k8s-app: {{app_name}}
  sessionAffinity: None
  type: ClusterIP